apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: testuser
  namespace: kafka-tutorial-kraft-east
  labels:
    strimzi.io/cluster: my-cluster-kraft
spec:
  authentication:
    type: tls