apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka-topics-helm
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-org/your-repo.git'
    targetRevision: HEAD
    path: charts/kafka-topics
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kafka-tutorial-kraft-east
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
