apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  name: app-user
  namespace: kafka-test
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
  authorization:
    type: simple
    acls:
      - operations: ["All"]
        resource:
          name: words
          patternType: literal
          type: topic
      - operations: ["All"]
        resource:
          name: mytopic
          patternType: literal
          type: topic
      - operations: ["Read"]
        resource:
          name: app-user
          patternType: literal
          type: group