apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: consumer-lag
  namespace: openshift-monitoring
  labels:
    app.kubernetes.io/managed-by: cluster-monitoring-operator
    app.kubernetes.io/name: kube-prometheus
    app.kubernetes.io/part-of: openshift-monitoring
    prometheus: k8s
    role: alert-rules
spec:
  groups:
    - name: kafka-lag-alerts
      rules:
        - alert: ConsumerLagHigh
          expr: |
            kafka_consumergroup_lag{consumergroup="my-group"} > 100
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Consumer group lag is too high"
            description: "Consumer group lag has exceeded 100 for over 5 minutes."
