apiVersion: v1
kind: Service
metadata:
  name: custom-kafka-jmx-metrics
  namespace: kafka-tutorial-kraft-east
  labels:
    app: strimzi-custom
    strimzi.io/cluster: my-cluster-kraft
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9404"
spec:
  ports:
  - name: metrics
    port: 9404
    protocol: TCP
    targetPort: 9404
  selector:
    strimzi.io/cluster: my-cluster-kraft
    strimzi.io/kind: Kafka
    strimzi.io/name: my-cluster-kraft-kafka
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: my-cluster-kraft-kafka-exporter
  namespace: kafka-tutorial-kraft-east
  labels:
    app: strimzi
    strimzi.io/cluster: my-cluster-kraft
    strimzi.io/kind: Kafka
    strimzi.io/name: my-cluster-kraft-kafka-exporter
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9404"
spec:
  ports:
  - name: metrics
    port: 9404
    protocol: TCP
    targetPort: 9404
  selector:
    strimzi.io/cluster: my-cluster-kraft
    strimzi.io/kind: Kafka
    strimzi.io/name: my-cluster-kraft-kafka-exporter
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-cluster-kraft-kafka-jmx
  namespace: kafka-tutorial-kraft-east
  labels:
    app: strimzi
spec:
  selector:
    matchLabels:
      app: strimzi-custom
      strimzi.io/cluster: my-cluster-kraft
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-cluster-kraft-kafka-exporter
  namespace: kafka-tutorial-kraft-east
  labels:
    app: strimzi
spec:
  selector:
    matchLabels:
      strimzi.io/cluster: my-cluster-kraft
      strimzi.io/kind: Kafka
      strimzi.io/name: my-cluster-kraft-kafka-exporter
  endpoints:
  - port: metrics
    interval: 15s
    path: /metrics