apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaMirrorMaker2
metadata:
  name: east-west-mirror-maker
  namespace: kafka-tutorial-kraft-east
spec:
  version: 3.9.0
  replicas: 1
  connectCluster: "west-cluster"
  clusters:
  - alias: "east-cluster"
    bootstrapServers: my-cluster-kraft-kafka-bootstrap-kafka-tutorial-kraft-east.apps.axolab.axodevelopment.dev:443
    tls:
      trustedCertificates:
        - secretName: my-cluster-kraft-cluster-ca-cert
          certificate: ca.crt
    authentication:
      type: tls
      certificateAndKey:
        secretName: mirror-maker-user-east
        certificate: user.crt
        key: user.key
  - alias: "west-cluster"
    bootstrapServers: my-cluster-kraft-kafka-bootstrap-kafka-tutorial-kraft-west.apps.axolab.axodevelopment.dev:443
    tls:
      trustedCertificates:
        - secretName: my-cluster-kraft-cluster-ca-cert-west
          certificate: ca.crt
    authentication:
      type: tls
      certificateAndKey:
        secretName: mirror-maker-user-west
        certificate: user.crt
        key: user.key
    config:
      config.storage.replication.factor: -1
      offset.storage.replication.factor: -1
      status.storage.replication.factor: -1
  mirrors:
  - sourceCluster: "east-cluster"
    targetCluster: "west-cluster"
    sourceConnector:
      tasksMax: 1
      config:
        replication.factor: -1
        offset-syncs.topic.replication.factor: -1
        sync.topic.acls.enabled: "false"
        refresh.topics.interval.seconds: 600
    checkpointConnector:
      tasksMax: 1
      config:
        checkpoints.topic.replication.factor: -1
        sync.group.offsets.enabled: "false"
        refresh.groups.interval.seconds: 600
    topicsPattern: ".*"
    groupsPattern: ".*"
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"
    limits:
      cpu: "1"
      memory: "1Gi"